"""
DocumenterCitationsExt

Package extension providing DocumenterCitations.jl support for DocumenterTypst.

This extension is automatically loaded when both DocumenterTypst and
DocumenterCitations are loaded. It adds support for rendering `@bibliography`
blocks and citation links in Typst/PDF output.

# Supported Features

- `@bibliography` blocks with `:dl`, `:ul`, and `:ol` list styles
- Canonical and non-canonical bibliography entries
- Automatic anchor generation for citation cross-references
- Citation links (handled automatically via ExpandCitations pipeline)
"""
module DocumenterCitationsExt

using DocumenterTypst: Context, _print, _println, typst, typstesc
using DocumenterTypst.TypstWriter: make_label_id, with_build_prefix
import DocumenterTypst: typst
using DocumenterCitations: BibliographyNode, BibliographyItem
using MarkdownAST: Node

"""
    typst(io::Context, node::Node, bib::BibliographyNode)

Render a bibliography block from DocumenterCitations to Typst format.

# List Style Mapping

| DocumenterCitations | Typst Output |
|---------------------|--------------|
| `:dl` (definition)  | Custom grid with label + reference |
| `:ul` (unordered)   | `- item` bullet list |
| `:ol` (ordered)     | `+ item` numbered list |

# Anchor Handling

For canonical bibliographies, each item gets a Typst label for cross-referencing:
```typst
#[] #label("citation-key")
```

Citation links are converted to `#link(label("citation-key"))` during the
ExpandCitations phase, so they work automatically with the anchors created here.
"""
function typst(io::Context, node::Node, bib::BibliographyNode)
    @assert node.element === bib

    # Empty bibliography - nothing to render
    isempty(bib.items) && return nothing

    _println(io)

    if bib.list_style == :dl
        # Definition list: render as grid with label and reference columns
        _typst_bibliography_dl(io, bib)
    elseif bib.list_style == :ol
        # Ordered list: use + for numbering
        _typst_bibliography_list(io, bib, '+')
    else
        # Unordered list (default): use - for bullets
        @assert bib.list_style == :ul
        _typst_bibliography_list(io, bib, '-')
    end

    _println(io)
    return nothing
end

"""
    _typst_bibliography_dl(io::Context, bib::BibliographyNode)

Render a definition-list style bibliography using Typst grid layout.
"""
function _typst_bibliography_dl(io::Context, bib::BibliographyNode)
    _println(io, "#grid(")
    _println(io, "  columns: (auto, 1fr),")
    _println(io, "  gutter: 1em,")

    for item in bib.items
        # Label column
        _print(io, "  [")
        if !isnothing(item.label)
            typst(io, item.label.children)
        end
        _print(io, "],")

        # Reference column with optional anchor
        _print(io, " [")
        _typst_anchor(io, item, bib.canonical)
        typst(io, item.reference.children)
        _println(io, "],")
    end

    return _println(io, ")")
end

"""
    _typst_bibliography_list(io::Context, bib::BibliographyNode, symbol::Char)

Render a list-style bibliography (ordered or unordered).
"""
function _typst_bibliography_list(io::Context, bib::BibliographyNode, symbol::Char)
    for item in bib.items
        _print(io, symbol, " ")
        _typst_anchor(io, item, bib.canonical)
        typst(io, item.reference.children)
        _println(io)
    end
    return
end

"""
    _typst_anchor(io::Context, item::BibliographyItem, canonical::Bool)

Output an invisible anchor for a bibliography item if it's in a canonical bibliography.

The anchor label must include the page prefix (e.g., `index.md#key`) to match
citation links generated by DocumenterCitations' ExpandCitations pipeline.
"""
function _typst_anchor(io::Context, item::BibliographyItem, canonical::Bool)
    return if canonical && !isnothing(item.anchor_key)
        # Create an invisible anchor point that citation links can reference
        # Use make_label_id to ensure consistent label format with citation links
        full_path = with_build_prefix(io.state, io.filename)
        label_id = make_label_id(io.doc, full_path, item.anchor_key)
        _print(io, "#[] #label(\"", label_id, "\") ")
    end
end

end # module
